### ISSUE TITLE
時間加速造成體力恢復時間縮短

### ISSUE THREAD

**Issue by henry3211439** [TSKModding/TSKHook#1]
如題，調高Time.timeScale會造成體力恢復時間縮短，不曉得官方會不會觀察到玩家體力恢復異常。

**Comment by c0re100** [comment]
這多出來的體力值實際上是用不到的
你隨便去一個界面就會回到原本的體力值了
只是本地顯示問題 3分鐘回1體變1分鐘回1體之類
伺服器仍然是3分鐘回1體
